/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapEsDotxmlRouteImport } from './routes/sitemap-es[.]xml'
import { Route as SitemapEnDotxmlRouteImport } from './routes/sitemap-en[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as ApiTrackClickRouteImport } from './routes/api.track-click'
import { Route as AdminSyncStatusRouteImport } from './routes/admin.sync-status'
import { Route as LocaleWatchChar123slugChar125RouteImport } from './routes/$locale.watch-{$slug}'
import { Route as LocaleVerChar123slugChar125RouteImport } from './routes/$locale.ver-{$slug}'
import { Route as LocaleTermsRouteImport } from './routes/$locale.terms'
import { Route as LocaleResponsibleGamblingRouteImport } from './routes/$locale.responsible-gambling'
import { Route as LocalePrivacyPolicyRouteImport } from './routes/$locale.privacy-policy'
import { Route as LocalePartnersRouteImport } from './routes/$locale.partners'
import { Route as LocaleHowToWatchWorldCupInChar123slugChar125RouteImport } from './routes/$locale.how-to-watch-world-cup-in-{$slug}'
import { Route as LocaleDondeVerMundialEnChar123slugChar125RouteImport } from './routes/$locale.donde-ver-mundial-en-{$slug}'
import { Route as LocaleBlogsRouteImport } from './routes/$locale.blogs'
import { Route as LocaleBlogsIndexRouteImport } from './routes/$locale.blogs.index'
import { Route as LocaleTeamSlugRouteImport } from './routes/$locale.team.$slug'
import { Route as LocaleBlogsSlugRouteImport } from './routes/$locale.blogs.$slug'
import { Route as ApiPublicHooksSyncFixturesRouteImport } from './routes/api/public/hooks/sync-fixtures'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEsDotxmlRoute = SitemapEsDotxmlRouteImport.update({
  id: '/sitemap-es.xml',
  path: '/sitemap-es.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapEnDotxmlRoute = SitemapEnDotxmlRouteImport.update({
  id: '/sitemap-en.xml',
  path: '/sitemap-en.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiTrackClickRoute = ApiTrackClickRouteImport.update({
  id: '/api/track-click',
  path: '/api/track-click',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSyncStatusRoute = AdminSyncStatusRouteImport.update({
  id: '/admin/sync-status',
  path: '/admin/sync-status',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWatchChar123slugChar125Route =
  LocaleWatchChar123slugChar125RouteImport.update({
    id: '/watch-{$slug}',
    path: '/watch-{$slug}',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleVerChar123slugChar125Route =
  LocaleVerChar123slugChar125RouteImport.update({
    id: '/ver-{$slug}',
    path: '/ver-{$slug}',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleTermsRoute = LocaleTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleResponsibleGamblingRoute =
  LocaleResponsibleGamblingRouteImport.update({
    id: '/responsible-gambling',
    path: '/responsible-gambling',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocalePrivacyPolicyRoute = LocalePrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePartnersRoute = LocalePartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHowToWatchWorldCupInChar123slugChar125Route =
  LocaleHowToWatchWorldCupInChar123slugChar125RouteImport.update({
    id: '/how-to-watch-world-cup-in-{$slug}',
    path: '/how-to-watch-world-cup-in-{$slug}',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleDondeVerMundialEnChar123slugChar125Route =
  LocaleDondeVerMundialEnChar123slugChar125RouteImport.update({
    id: '/donde-ver-mundial-en-{$slug}',
    path: '/donde-ver-mundial-en-{$slug}',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleBlogsRoute = LocaleBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogsIndexRoute = LocaleBlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleBlogsRoute,
} as any)
const LocaleTeamSlugRoute = LocaleTeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogsSlugRoute = LocaleBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleBlogsRoute,
} as any)
const ApiPublicHooksSyncFixturesRoute =
  ApiPublicHooksSyncFixturesRouteImport.update({
    id: '/api/public/hooks/sync-fixtures',
    path: '/api/public/hooks/sync-fixtures',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/blogs': typeof LocaleBlogsRouteWithChildren
  '/$locale/donde-ver-mundial-en-{$slug}': typeof LocaleDondeVerMundialEnChar123slugChar125Route
  '/$locale/how-to-watch-world-cup-in-{$slug}': typeof LocaleHowToWatchWorldCupInChar123slugChar125Route
  '/$locale/partners': typeof LocalePartnersRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/responsible-gambling': typeof LocaleResponsibleGamblingRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/ver-{$slug}': typeof LocaleVerChar123slugChar125Route
  '/$locale/watch-{$slug}': typeof LocaleWatchChar123slugChar125Route
  '/admin/sync-status': typeof AdminSyncStatusRoute
  '/api/track-click': typeof ApiTrackClickRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blogs/$slug': typeof LocaleBlogsSlugRoute
  '/$locale/team/$slug': typeof LocaleTeamSlugRoute
  '/$locale/blogs/': typeof LocaleBlogsIndexRoute
  '/api/public/hooks/sync-fixtures': typeof ApiPublicHooksSyncFixturesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/donde-ver-mundial-en-{$slug}': typeof LocaleDondeVerMundialEnChar123slugChar125Route
  '/$locale/how-to-watch-world-cup-in-{$slug}': typeof LocaleHowToWatchWorldCupInChar123slugChar125Route
  '/$locale/partners': typeof LocalePartnersRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/responsible-gambling': typeof LocaleResponsibleGamblingRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/ver-{$slug}': typeof LocaleVerChar123slugChar125Route
  '/$locale/watch-{$slug}': typeof LocaleWatchChar123slugChar125Route
  '/admin/sync-status': typeof AdminSyncStatusRoute
  '/api/track-click': typeof ApiTrackClickRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blogs/$slug': typeof LocaleBlogsSlugRoute
  '/$locale/team/$slug': typeof LocaleTeamSlugRoute
  '/$locale/blogs': typeof LocaleBlogsIndexRoute
  '/api/public/hooks/sync-fixtures': typeof ApiPublicHooksSyncFixturesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-en.xml': typeof SitemapEnDotxmlRoute
  '/sitemap-es.xml': typeof SitemapEsDotxmlRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/blogs': typeof LocaleBlogsRouteWithChildren
  '/$locale/donde-ver-mundial-en-{$slug}': typeof LocaleDondeVerMundialEnChar123slugChar125Route
  '/$locale/how-to-watch-world-cup-in-{$slug}': typeof LocaleHowToWatchWorldCupInChar123slugChar125Route
  '/$locale/partners': typeof LocalePartnersRoute
  '/$locale/privacy-policy': typeof LocalePrivacyPolicyRoute
  '/$locale/responsible-gambling': typeof LocaleResponsibleGamblingRoute
  '/$locale/terms': typeof LocaleTermsRoute
  '/$locale/ver-{$slug}': typeof LocaleVerChar123slugChar125Route
  '/$locale/watch-{$slug}': typeof LocaleWatchChar123slugChar125Route
  '/admin/sync-status': typeof AdminSyncStatusRoute
  '/api/track-click': typeof ApiTrackClickRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blogs/$slug': typeof LocaleBlogsSlugRoute
  '/$locale/team/$slug': typeof LocaleTeamSlugRoute
  '/$locale/blogs/': typeof LocaleBlogsIndexRoute
  '/api/public/hooks/sync-fixtures': typeof ApiPublicHooksSyncFixturesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/robots.txt'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/$locale/blogs'
    | '/$locale/donde-ver-mundial-en-{$slug}'
    | '/$locale/how-to-watch-world-cup-in-{$slug}'
    | '/$locale/partners'
    | '/$locale/privacy-policy'
    | '/$locale/responsible-gambling'
    | '/$locale/terms'
    | '/$locale/ver-{$slug}'
    | '/$locale/watch-{$slug}'
    | '/admin/sync-status'
    | '/api/track-click'
    | '/$locale/'
    | '/$locale/blogs/$slug'
    | '/$locale/team/$slug'
    | '/$locale/blogs/'
    | '/api/public/hooks/sync-fixtures'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/$locale/donde-ver-mundial-en-{$slug}'
    | '/$locale/how-to-watch-world-cup-in-{$slug}'
    | '/$locale/partners'
    | '/$locale/privacy-policy'
    | '/$locale/responsible-gambling'
    | '/$locale/terms'
    | '/$locale/ver-{$slug}'
    | '/$locale/watch-{$slug}'
    | '/admin/sync-status'
    | '/api/track-click'
    | '/$locale'
    | '/$locale/blogs/$slug'
    | '/$locale/team/$slug'
    | '/$locale/blogs'
    | '/api/public/hooks/sync-fixtures'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/robots.txt'
    | '/sitemap-en.xml'
    | '/sitemap-es.xml'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/$locale/blogs'
    | '/$locale/donde-ver-mundial-en-{$slug}'
    | '/$locale/how-to-watch-world-cup-in-{$slug}'
    | '/$locale/partners'
    | '/$locale/privacy-policy'
    | '/$locale/responsible-gambling'
    | '/$locale/terms'
    | '/$locale/ver-{$slug}'
    | '/$locale/watch-{$slug}'
    | '/admin/sync-status'
    | '/api/track-click'
    | '/$locale/'
    | '/$locale/blogs/$slug'
    | '/$locale/team/$slug'
    | '/$locale/blogs/'
    | '/api/public/hooks/sync-fixtures'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapEnDotxmlRoute: typeof SitemapEnDotxmlRoute
  SitemapEsDotxmlRoute: typeof SitemapEsDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminSyncStatusRoute: typeof AdminSyncStatusRoute
  ApiTrackClickRoute: typeof ApiTrackClickRoute
  ApiPublicHooksSyncFixturesRoute: typeof ApiPublicHooksSyncFixturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-es.xml': {
      id: '/sitemap-es.xml'
      path: '/sitemap-es.xml'
      fullPath: '/sitemap-es.xml'
      preLoaderRoute: typeof SitemapEsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-en.xml': {
      id: '/sitemap-en.xml'
      path: '/sitemap-en.xml'
      fullPath: '/sitemap-en.xml'
      preLoaderRoute: typeof SitemapEnDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/track-click': {
      id: '/api/track-click'
      path: '/api/track-click'
      fullPath: '/api/track-click'
      preLoaderRoute: typeof ApiTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sync-status': {
      id: '/admin/sync-status'
      path: '/admin/sync-status'
      fullPath: '/admin/sync-status'
      preLoaderRoute: typeof AdminSyncStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/watch-{$slug}': {
      id: '/$locale/watch-{$slug}'
      path: '/watch-{$slug}'
      fullPath: '/$locale/watch-{$slug}'
      preLoaderRoute: typeof LocaleWatchChar123slugChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ver-{$slug}': {
      id: '/$locale/ver-{$slug}'
      path: '/ver-{$slug}'
      fullPath: '/$locale/ver-{$slug}'
      preLoaderRoute: typeof LocaleVerChar123slugChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/terms': {
      id: '/$locale/terms'
      path: '/terms'
      fullPath: '/$locale/terms'
      preLoaderRoute: typeof LocaleTermsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/responsible-gambling': {
      id: '/$locale/responsible-gambling'
      path: '/responsible-gambling'
      fullPath: '/$locale/responsible-gambling'
      preLoaderRoute: typeof LocaleResponsibleGamblingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/privacy-policy': {
      id: '/$locale/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/$locale/privacy-policy'
      preLoaderRoute: typeof LocalePrivacyPolicyRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/partners': {
      id: '/$locale/partners'
      path: '/partners'
      fullPath: '/$locale/partners'
      preLoaderRoute: typeof LocalePartnersRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/how-to-watch-world-cup-in-{$slug}': {
      id: '/$locale/how-to-watch-world-cup-in-{$slug}'
      path: '/how-to-watch-world-cup-in-{$slug}'
      fullPath: '/$locale/how-to-watch-world-cup-in-{$slug}'
      preLoaderRoute: typeof LocaleHowToWatchWorldCupInChar123slugChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/donde-ver-mundial-en-{$slug}': {
      id: '/$locale/donde-ver-mundial-en-{$slug}'
      path: '/donde-ver-mundial-en-{$slug}'
      fullPath: '/$locale/donde-ver-mundial-en-{$slug}'
      preLoaderRoute: typeof LocaleDondeVerMundialEnChar123slugChar125RouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blogs': {
      id: '/$locale/blogs'
      path: '/blogs'
      fullPath: '/$locale/blogs'
      preLoaderRoute: typeof LocaleBlogsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blogs/': {
      id: '/$locale/blogs/'
      path: '/'
      fullPath: '/$locale/blogs/'
      preLoaderRoute: typeof LocaleBlogsIndexRouteImport
      parentRoute: typeof LocaleBlogsRoute
    }
    '/$locale/team/$slug': {
      id: '/$locale/team/$slug'
      path: '/team/$slug'
      fullPath: '/$locale/team/$slug'
      preLoaderRoute: typeof LocaleTeamSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blogs/$slug': {
      id: '/$locale/blogs/$slug'
      path: '/$slug'
      fullPath: '/$locale/blogs/$slug'
      preLoaderRoute: typeof LocaleBlogsSlugRouteImport
      parentRoute: typeof LocaleBlogsRoute
    }
    '/api/public/hooks/sync-fixtures': {
      id: '/api/public/hooks/sync-fixtures'
      path: '/api/public/hooks/sync-fixtures'
      fullPath: '/api/public/hooks/sync-fixtures'
      preLoaderRoute: typeof ApiPublicHooksSyncFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleBlogsRouteChildren {
  LocaleBlogsSlugRoute: typeof LocaleBlogsSlugRoute
  LocaleBlogsIndexRoute: typeof LocaleBlogsIndexRoute
}

const LocaleBlogsRouteChildren: LocaleBlogsRouteChildren = {
  LocaleBlogsSlugRoute: LocaleBlogsSlugRoute,
  LocaleBlogsIndexRoute: LocaleBlogsIndexRoute,
}

const LocaleBlogsRouteWithChildren = LocaleBlogsRoute._addFileChildren(
  LocaleBlogsRouteChildren,
)

interface LocaleRouteChildren {
  LocaleBlogsRoute: typeof LocaleBlogsRouteWithChildren
  LocaleDondeVerMundialEnChar123slugChar125Route: typeof LocaleDondeVerMundialEnChar123slugChar125Route
  LocaleHowToWatchWorldCupInChar123slugChar125Route: typeof LocaleHowToWatchWorldCupInChar123slugChar125Route
  LocalePartnersRoute: typeof LocalePartnersRoute
  LocalePrivacyPolicyRoute: typeof LocalePrivacyPolicyRoute
  LocaleResponsibleGamblingRoute: typeof LocaleResponsibleGamblingRoute
  LocaleTermsRoute: typeof LocaleTermsRoute
  LocaleVerChar123slugChar125Route: typeof LocaleVerChar123slugChar125Route
  LocaleWatchChar123slugChar125Route: typeof LocaleWatchChar123slugChar125Route
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleTeamSlugRoute: typeof LocaleTeamSlugRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleBlogsRoute: LocaleBlogsRouteWithChildren,
  LocaleDondeVerMundialEnChar123slugChar125Route:
    LocaleDondeVerMundialEnChar123slugChar125Route,
  LocaleHowToWatchWorldCupInChar123slugChar125Route:
    LocaleHowToWatchWorldCupInChar123slugChar125Route,
  LocalePartnersRoute: LocalePartnersRoute,
  LocalePrivacyPolicyRoute: LocalePrivacyPolicyRoute,
  LocaleResponsibleGamblingRoute: LocaleResponsibleGamblingRoute,
  LocaleTermsRoute: LocaleTermsRoute,
  LocaleVerChar123slugChar125Route: LocaleVerChar123slugChar125Route,
  LocaleWatchChar123slugChar125Route: LocaleWatchChar123slugChar125Route,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleTeamSlugRoute: LocaleTeamSlugRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapEnDotxmlRoute: SitemapEnDotxmlRoute,
  SitemapEsDotxmlRoute: SitemapEsDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminSyncStatusRoute: AdminSyncStatusRoute,
  ApiTrackClickRoute: ApiTrackClickRoute,
  ApiPublicHooksSyncFixturesRoute: ApiPublicHooksSyncFixturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
